# Site settings
title: Die Full Service Werbeagentur Köln – ep-communication.de

description: "Strategie, Kreation & Realisierung von effektiven Ideen, die begeistern: für B2B & B2C, online & offline #weilwireskönnen"
url: "http://www.ep-communication.de" # the base hostname & protocol for your site

twitter: https://twitter.com/ep_comm_gmbh
xing: https://www.xing.com/companies/epcommunicationgmbh
facebook: https://www.facebook.com/epcommunicationgmbh
instagram: https://www.instagram.com/epcommunication/



# Build settings
markdown: kramdown

collections: 
  projects:
    output: true
  jobs:
    output: true

_comments:
  tags: "Auflistung mit Komma trennen"