# Site settings
title: Die Full Service Werbeagentur Köln – epcommunication.de

description: "Strategie, Kreation & Realisierung von effektiven Ideen, die begeistern: für B2B & B2C, online & offline #weilwireskönnen"
url: "http://www.ep-communication.de" # the base hostname & protocol for your site
twitter_username: ep-communication
github_username:  ep-communication

company_name: ep communication GmbH
address: Bayenthalgürtel 7
plz: 50968 Köln
tel: +49 (0)221 96 98 95-90
fax: +49 (0)221 96 98 95-96
ceo: Emitis Pohl
amtsgericht: Köln HRB 76168
ust-nr: DE284 154 502
contact_email: info@ep-communication.de
web: www.ep-communication.de

# Build settings
markdown: kramdown

collections: 
  projects:
    output: true
  clients: